#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v2
# autospec commit: 250a6667ebd1
#
# Source0 file verified with key 0x42061031267D11B1 (jimklimov@gmail.com)
#
Name     : nut
Version  : 2.8.1
Release  : 1
URL      : https://github.com/networkupstools/nut/releases/download/v2.8.1/nut-2.8.1.tar.gz
Source0  : https://github.com/networkupstools/nut/releases/download/v2.8.1/nut-2.8.1.tar.gz
Source1  : https://github.com/networkupstools/nut/releases/download/v2.8.1/nut-2.8.1.tar.gz.sig
Summary  : Power devices discovery with Network UPS Tools
Group    : Development/Tools
License  : GPL-2.0 GPL-3.0
Requires: nut-bin = %{version}-%{release}
Requires: nut-config = %{version}-%{release}
Requires: nut-data = %{version}-%{release}
Requires: nut-lib = %{version}-%{release}
Requires: nut-libexec = %{version}-%{release}
Requires: nut-license = %{version}-%{release}
Requires: nut-man = %{version}-%{release}
Requires: nut-python = %{version}-%{release}
Requires: nut-python3 = %{version}-%{release}
Requires: nut-services = %{version}-%{release}
BuildRequires : asciidoc
BuildRequires : aspell-dev
BuildRequires : buildreq-configure
BuildRequires : cppcheck
BuildRequires : libxml2-dev
BuildRequires : libxslt-bin
BuildRequires : openssl-dev
BuildRequires : pkgconfig(cppunit)
BuildRequires : systemd-dev
BuildRequires : valgrind
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description


%package bin
Summary: bin components for the nut package.
Group: Binaries
Requires: nut-data = %{version}-%{release}
Requires: nut-libexec = %{version}-%{release}
Requires: nut-config = %{version}-%{release}
Requires: nut-license = %{version}-%{release}
Requires: nut-services = %{version}-%{release}

%description bin
bin components for the nut package.


%package config
Summary: config components for the nut package.
Group: Default

%description config
config components for the nut package.


%package data
Summary: data components for the nut package.
Group: Data

%description data
data components for the nut package.


%package dev
Summary: dev components for the nut package.
Group: Development
Requires: nut-lib = %{version}-%{release}
Requires: nut-bin = %{version}-%{release}
Requires: nut-data = %{version}-%{release}
Provides: nut-devel = %{version}-%{release}
Requires: nut = %{version}-%{release}

%description dev
dev components for the nut package.


%package lib
Summary: lib components for the nut package.
Group: Libraries
Requires: nut-data = %{version}-%{release}
Requires: nut-libexec = %{version}-%{release}
Requires: nut-license = %{version}-%{release}

%description lib
lib components for the nut package.


%package libexec
Summary: libexec components for the nut package.
Group: Default
Requires: nut-config = %{version}-%{release}
Requires: nut-license = %{version}-%{release}

%description libexec
libexec components for the nut package.


%package license
Summary: license components for the nut package.
Group: Default

%description license
license components for the nut package.


%package man
Summary: man components for the nut package.
Group: Default

%description man
man components for the nut package.


%package python
Summary: python components for the nut package.
Group: Default
Requires: nut-python3 = %{version}-%{release}

%description python
python components for the nut package.


%package python3
Summary: python3 components for the nut package.
Group: Default
Requires: python3-core

%description python3
python3 components for the nut package.


%package services
Summary: services components for the nut package.
Group: Systemd services
Requires: systemd

%description services
services components for the nut package.


%prep
%setup -q -n nut-2.8.1
cd %{_builddir}/nut-2.8.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1699893076
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1699893076
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/nut
cp %{_builddir}/nut-%{version}/LICENSE-GPL2 %{buildroot}/usr/share/package-licenses/nut/06877624ea5c77efe3b7e39b0f909eda6e25a4ec || :
cp %{_builddir}/nut-%{version}/LICENSE-GPL3 %{buildroot}/usr/share/package-licenses/nut/842745cb706f8f2126506f544492f7a80dbe29b3 || :
%make_install

%files
%defattr(-,root,root,-)
/usr/lib/systemd/system-shutdown/nutshutdown

%files bin
%defattr(-,root,root,-)
/usr/bin/al175
/usr/bin/apcsmart
/usr/bin/apcsmart-old
/usr/bin/apcupsd-ups
/usr/bin/bcmxcp
/usr/bin/belkin
/usr/bin/belkinunv
/usr/bin/bestfcom
/usr/bin/bestfortress
/usr/bin/bestuferrups
/usr/bin/bestups
/usr/bin/blazer_ser
/usr/bin/clone
/usr/bin/clone-outlet
/usr/bin/dummy-ups
/usr/bin/etapro
/usr/bin/everups
/usr/bin/gamatronic
/usr/bin/genericups
/usr/bin/isbmex
/usr/bin/ivtscd
/usr/bin/liebert
/usr/bin/liebert-esp2
/usr/bin/masterguard
/usr/bin/metasys
/usr/bin/mge-shut
/usr/bin/mge-utalk
/usr/bin/microdowell
/usr/bin/microsol-apc
/usr/bin/nut-scanner
/usr/bin/nutdrv_qx
/usr/bin/nutdrv_siemens-sitop
/usr/bin/oneac
/usr/bin/optiups
/usr/bin/powercom
/usr/bin/powerpanel
/usr/bin/rhino
/usr/bin/riello_ser
/usr/bin/safenet
/usr/bin/skel
/usr/bin/sms_ser
/usr/bin/solis
/usr/bin/tripplite
/usr/bin/tripplitesu
/usr/bin/upsc
/usr/bin/upscmd
/usr/bin/upscode2
/usr/bin/upsd
/usr/bin/upsdrvctl
/usr/bin/upsdrvsvcctl
/usr/bin/upslog
/usr/bin/upsmon
/usr/bin/upsrw
/usr/bin/upssched
/usr/bin/upssched-cmd
/usr/bin/victronups

%files config
%defattr(-,root,root,-)
/usr/lib/tmpfiles.d/nut-common-tmpfiles.conf

%files data
%defattr(-,root,root,-)
/usr/share/cmdvartab
/usr/share/driver.list

%files dev
%defattr(-,root,root,-)
/usr/lib64/libnutclient.so
/usr/lib64/libnutclientstub.so
/usr/lib64/libnutscan.so
/usr/lib64/libupsclient.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libnutclient.so.2
/usr/lib64/libnutclient.so.2.0.2
/usr/lib64/libnutclientstub.so.1
/usr/lib64/libnutclientstub.so.1.0.1
/usr/lib64/libnutscan.so.2
/usr/lib64/libnutscan.so.2.0.2
/usr/lib64/libupsclient.so.6
/usr/lib64/libupsclient.so.6.0.1

%files libexec
%defattr(-,root,root,-)
/usr/libexec/nut-driver-enumerator.sh

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/nut/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
/usr/share/package-licenses/nut/842745cb706f8f2126506f544492f7a80dbe29b3

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man5/nut.conf.5
/usr/share/man/man5/ups.conf.5
/usr/share/man/man5/upsd.conf.5
/usr/share/man/man5/upsd.users.5
/usr/share/man/man5/upsmon.conf.5
/usr/share/man/man5/upssched.conf.5
/usr/share/man/man8/al175.8
/usr/share/man/man8/apcsmart-old.8
/usr/share/man/man8/apcsmart.8
/usr/share/man/man8/apcupsd-ups.8
/usr/share/man/man8/bcmxcp.8
/usr/share/man/man8/belkin.8
/usr/share/man/man8/belkinunv.8
/usr/share/man/man8/bestfcom.8
/usr/share/man/man8/bestfortress.8
/usr/share/man/man8/bestuferrups.8
/usr/share/man/man8/bestups.8
/usr/share/man/man8/blazer_ser.8
/usr/share/man/man8/clone.8
/usr/share/man/man8/dummy-ups.8
/usr/share/man/man8/etapro.8
/usr/share/man/man8/everups.8
/usr/share/man/man8/gamatronic.8
/usr/share/man/man8/genericups.8
/usr/share/man/man8/isbmex.8
/usr/share/man/man8/ivtscd.8
/usr/share/man/man8/liebert-esp2.8
/usr/share/man/man8/liebert.8
/usr/share/man/man8/masterguard.8
/usr/share/man/man8/metasys.8
/usr/share/man/man8/mge-shut.8
/usr/share/man/man8/mge-utalk.8
/usr/share/man/man8/microdowell.8
/usr/share/man/man8/microsol-apc.8
/usr/share/man/man8/nut-driver-enumerator.8
/usr/share/man/man8/nut-recorder.8
/usr/share/man/man8/nut-scanner.8
/usr/share/man/man8/nutdrv_qx.8
/usr/share/man/man8/nutdrv_siemens_sitop.8
/usr/share/man/man8/nutupsdrv.8
/usr/share/man/man8/oneac.8
/usr/share/man/man8/optiups.8
/usr/share/man/man8/powercom.8
/usr/share/man/man8/powerpanel.8
/usr/share/man/man8/rhino.8
/usr/share/man/man8/riello_ser.8
/usr/share/man/man8/safenet.8
/usr/share/man/man8/sms_ser.8
/usr/share/man/man8/solis.8
/usr/share/man/man8/tripplite.8
/usr/share/man/man8/tripplitesu.8
/usr/share/man/man8/upsc.8
/usr/share/man/man8/upscmd.8
/usr/share/man/man8/upscode2.8
/usr/share/man/man8/upsd.8
/usr/share/man/man8/upsdrvctl.8
/usr/share/man/man8/upsdrvsvcctl.8
/usr/share/man/man8/upslog.8
/usr/share/man/man8/upsmon.8
/usr/share/man/man8/upsrw.8
/usr/share/man/man8/upssched.8
/usr/share/man/man8/victronups.8

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/nut-driver-enumerator.path
/usr/lib/systemd/system/nut-driver-enumerator.service
/usr/lib/systemd/system/nut-driver.target
/usr/lib/systemd/system/nut-driver@.service
/usr/lib/systemd/system/nut-monitor.service
/usr/lib/systemd/system/nut-server.service
/usr/lib/systemd/system/nut.target
